apiVersion: v2
name: calert
version: 0.0.0-dev
description: A Helm chart for the calert which uses Alertmanager webhook receiver to receive alerts payload, and pushes this data to Google Chat webhook endpoint.
type: application
keywords:
  - monitoring
  - alerting
  - prometheus
  - alertmanager
  - alertmanager-webhook
  - google-chat
home: https://github.com/shpeliving/calert
sources:
  - https://github.com/shpeliving/calert
maintainers:
  - name: Karan Sharma
    email: hello@mrkaran.dev
    url: https://github.com/mr-karan
  - name: Alex Kolakov
    email: aleksandar.kolakov@primeholding.com
    url: https://github.com/alexkolakovprime
appVersion: 0.0.0-dev
